name: game_launcher
description: GAME_LAUNCHER - Pyxel game WebView wrapper

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  path_provider: ^2.1.2
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/docs/R_P__G___8bit.html
    - assets/docs/Cubeboy.html
    - assets/docs/lineboy.html
